name: CI Pipeline


on:
  push:
  workflow_dispatch:


jobs:

  lint:
    name: Linter
    runs-on: macOS-latest
    steps:

      - name: Clone Code
        uses: actions/checkout@v2

      - name: Run Linter
        run: make lint -B